[package]
name = "parcom"
version = "0.0.0"
edition = "2021"


[dependencies]
parcom-std = { path = "../parcom-std", version = "0.0.0" }
parcom-core = { path = "../parcom-core", version = "0.0.0" }

[features]
default = ["std", "primitive"]
std = ["primitive"]
primitive = ["parcom-core/primitive"]
